import { Trip, Alternative, ChangeSummary, AgentStep, AgentMessage } from '../types/trip';

export const INITIAL_MOCK_TRIP: Trip = {
  trip_id: 'trip_001',
  destination: 'Paris, France',
  dates: {
    start: '2026-10-10',
    end: '2026-10-14',
  },
  status: 'active',
  budget: {
    target_cap: 50000,
    estimated_total: 45000,
    currency: 'INR',
    remaining: 5000,
    contingency_status: 'healthy',
    breakdown: [
      { category: 'Sightseeing & Culture', amount: 16500, percentage: 36.7, color: '#0284c7' },
      { category: 'Dining & Cafés', amount: 14000, percentage: 31.1, color: '#10b981' },
      { category: 'Local Transit', amount: 6500, percentage: 14.4, color: '#565e74' },
      { category: 'Stays & Staging', amount: 8000, percentage: 17.8, color: '#8b5cf6' },
    ],
  },
  constraints: {
    destination: 'Paris, France',
    start_date: '2026-10-10',
    end_date: '2026-10-14',
    budget: 50000,
    currency: 'INR',
    interests: ['Museums', 'French Cuisine', 'Historic Landmarks', 'Architecture'],
    preferences: {
      preferred_start_time: '09:00',
      preferred_end_time: '21:00',
      max_activity_travel_minutes: 35,
      activity_intensity: 'moderate',
    },
  },
  accommodation: {
    name: 'Hôtel Saint-Germain Des Prés',
    address: 'Rue Bonaparte, 6th Arrondissement, Paris',
    check_in: '2026-10-10 14:00',
    check_out: '2026-10-14 11:00',
  },
  itinerary: {
    days: [
      {
        day_number: 1,
        date: '2026-10-10',
        title: 'Arrival & Historic Core',
        theme: 'Classical monuments, royal gardens, and Seine sunset',
        daily_cost: 11500,
        currency: 'INR',
        walking_distance_km: 3.8,
        walking_duration_minutes: 48,
        conflicts_count: 0,
        activities: [
          {
            id: 'act_001_flight',
            name: 'Air France AF1824 Arrival',
            type: 'flight',
            location: 'CDG Terminal 2E',
            start_time: '09:15',
            end_time: '10:00',
            duration_minutes: 45,
            estimated_cost: 0,
            currency: 'INR',
            description: 'Baggage claim carousel 4 • Priority lane • Fast-track transit ready',
            status: 'confirmed',
            status_label: 'On Schedule',
            tags: ['Flight', 'Arrival'],
            transit_after: {
              type: 'train',
              duration_minutes: 30,
              distance_km: 26,
              from_location: 'CDG Airport',
              to_location: 'Paris City Center',
              path_type: 'RER B Express',
              notes: '30 min non-stop express link into central Paris network',
            },
          },
          {
            id: 'act_002_louvre',
            name: 'Louvre Museum Timed Entry',
            type: 'museum',
            location: 'Rue de Rivoli, 1er Arrondissement',
            start_time: '10:30',
            end_time: '13:00',
            duration_minutes: 150,
            estimated_cost: 2200,
            currency: 'INR',
            description: 'Audio guided master tour • Pre-paid entry voucher #PV-9912 • Wing Denon',
            status: 'planned',
            status_label: 'Pass Verified',
            tags: ['Museum', 'Art', 'Landmark'],
            cancellation_policy: 'Free cancellation window until 08:30 today',
            image_url:
              'https://images.unsplash.com/photo-1565099824688-e93eb20fe527?auto=format&fit=crop&w=600&q=80',
            transit_after: {
              type: 'walk',
              duration_minutes: 15,
              distance_km: 0.9,
              from_location: 'Louvre Museum',
              to_location: 'Tuileries Garden Bistro',
              path_type: 'Optimal Path',
              notes: '15 min scenic walk across Cour Carrée & Pont des Arts',
            },
          },
          {
            id: 'act_003_lunch',
            name: 'Lunch at Le Jardin des Tuileries Bistro',
            type: 'dining',
            location: 'Jardin des Tuileries',
            start_time: '13:15',
            end_time: '14:30',
            duration_minutes: 75,
            estimated_cost: 2000,
            currency: 'INR',
            description: 'Outdoor terrace seating • Organic quiche, duck confit & artisanal cider',
            status: 'confirmed',
            status_label: 'Table Reserved',
            tags: ['Food', 'Terrace', 'French'],
            image_url:
              'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=600&q=80',
            transit_after: {
              type: 'metro',
              duration_minutes: 25,
              distance_km: 2.1,
              from_location: 'Tuileries',
              to_location: 'Port de la Bourdonnais',
              path_type: 'Direct (RER C)',
              notes: '25 min transit via RER C along the Left Bank promenade',
            },
          },
          {
            id: 'act_004_cruise',
            name: 'Seine River Architectural Cruise',
            type: 'sightseeing',
            location: 'Port de la Bourdonnais, Pier 3',
            start_time: '15:00',
            end_time: '17:30',
            duration_minutes: 150,
            estimated_cost: 2800,
            currency: 'INR',
            description: 'Open-deck glass boat • Audio-guided historic panorama through 32 Parisian bridges',
            status: 'confirmed',
            status_label: 'Pass Verified',
            tags: ['Sightseeing', 'River', 'Panorama'],
            image_url:
              'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=600&q=80',
            transit_after: {
              type: 'walk',
              duration_minutes: 15,
              distance_km: 0.8,
              from_location: 'Seine Pier 3',
              to_location: 'Champ de Mars / Eiffel Tower',
              path_type: 'Low Congestion',
              notes: '15 min walk through landscaped gardens of Champ de Mars',
            },
          },
          {
            id: 'act_005_eiffel',
            name: 'Eiffel Tower Sunset View & Dinner',
            type: 'landmark',
            location: 'Champ de Mars, 5 Av. Anatole France',
            start_time: '18:30',
            end_time: '20:30',
            duration_minutes: 120,
            estimated_cost: 4500,
            currency: 'INR',
            description: 'Madame Brasserie (1st Floor) • Golden hour twilight view & 3-course tasting menu',
            status: 'confirmed',
            status_label: 'Table Reserved',
            tags: ['Landmark', 'Dinner', 'Iconic'],
            image_url:
              'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=600&q=80',
          },
        ],
      },
      {
        day_number: 2,
        date: '2026-10-11',
        title: 'Art, Left Bank & Bohemian Cafés',
        theme: 'Impressionist galleries, Latin Quarter alleyways, and iconic bookshops',
        daily_cost: 10800,
        currency: 'INR',
        walking_distance_km: 4.2,
        walking_duration_minutes: 55,
        conflicts_count: 0,
        activities: [
          {
            id: 'act_201',
            name: "Musée de l'Orangerie (Monet's Water Lilies)",
            type: 'museum',
            location: 'Jardin des Tuileries',
            start_time: '09:30',
            end_time: '11:30',
            duration_minutes: 120,
            estimated_cost: 1800,
            currency: 'INR',
            description: 'Oval galleries dedicated to Claude Monet panoramic Nymphéas masterpieces',
            status: 'confirmed',
            status_label: 'Pass Verified',
            tags: ['Art', 'Museum', 'Monet'],
            transit_after: {
              type: 'walk',
              duration_minutes: 12,
              distance_km: 0.7,
              from_location: "Musée de l'Orangerie",
              to_location: 'Café de Flore',
              path_type: 'Scenic Boulevard',
              notes: 'Stroll across Pont Royal into Boulevard Saint-Germain',
            },
          },
          {
            id: 'act_202',
            name: 'Saint-Germain-des-Prés Historic Café & Lunch',
            type: 'dining',
            location: '172 Boulevard Saint-Germain',
            start_time: '12:00',
            end_time: '13:30',
            duration_minutes: 90,
            estimated_cost: 2400,
            currency: 'INR',
            description: 'Classic literary café • Croque Monsieur, French onion soup & hot chocolate',
            status: 'confirmed',
            status_label: 'Confirmed',
            tags: ['Food', 'Café', 'Historic'],
            transit_after: {
              type: 'walk',
              duration_minutes: 10,
              distance_km: 0.6,
              from_location: 'Saint-Germain',
              to_location: 'Jardin du Luxembourg',
              path_type: 'Pedestrian Alley',
              notes: 'Walk past church of Saint-Sulpice',
            },
          },
          {
            id: 'act_203',
            name: 'Jardin du Luxembourg & Latin Quarter',
            type: 'leisure',
            location: '6th Arrondissement',
            start_time: '14:00',
            end_time: '16:30',
            duration_minutes: 150,
            estimated_cost: 600,
            currency: 'INR',
            description: 'Palace gardens, Medici fountain, and historic Sorbonne university streets',
            status: 'planned',
            status_label: 'Open Access',
            tags: ['Parks', 'Architecture', 'Culture'],
            transit_after: {
              type: 'walk',
              duration_minutes: 15,
              distance_km: 0.8,
              from_location: 'Luxembourg',
              to_location: 'Shakespeare & Co',
              path_type: 'Pedestrian Route',
              notes: 'Down Rue Saint-Jacques toward the Seine',
            },
          },
          {
            id: 'act_204',
            name: 'Shakespeare and Company & Panthéon View',
            type: 'landmark',
            location: '37 Rue de la Bûcherie',
            start_time: '17:00',
            end_time: '19:00',
            duration_minutes: 120,
            estimated_cost: 1500,
            currency: 'INR',
            description: 'Legendary English-language bookstore facing Notre-Dame cathedral square',
            status: 'planned',
            status_label: 'Scheduled',
            tags: ['Books', 'Landmark', 'History'],
          },
        ],
      },
      {
        day_number: 3,
        date: '2026-10-12',
        title: 'Montmartre & Panoramic Paris',
        theme: 'Hilltop basilicas, winding cobblestones, and opera grandeur',
        daily_cost: 11200,
        currency: 'INR',
        walking_distance_km: 5.1,
        walking_duration_minutes: 65,
        conflicts_count: 0,
        activities: [
          {
            id: 'act_301',
            name: 'Sacré-Cœur Basilica & Place du Tertre',
            type: 'landmark',
            location: '35 Rue du Chevalier de la Barre',
            start_time: '09:30',
            end_time: '12:00',
            duration_minutes: 150,
            estimated_cost: 1200,
            currency: 'INR',
            description: 'Hilltop views over all Paris, artist easel square, and historic Montmartre vineyards',
            status: 'confirmed',
            status_label: 'Confirmed',
            tags: ['Viewpoint', 'Basilica', 'Art'],
          },
          {
            id: 'act_302',
            name: 'Traditional Montmartre Bistro Lunch',
            type: 'dining',
            location: 'Rue des Abbesses',
            start_time: '12:30',
            end_time: '14:00',
            duration_minutes: 90,
            estimated_cost: 2200,
            currency: 'INR',
            description: 'Boeuf bourguignon, fresh ratatouille, and tarte tatin at traditional neighborhood bistro',
            status: 'confirmed',
            status_label: 'Table Reserved',
            tags: ['Food', 'Bistro'],
          },
          {
            id: 'act_303',
            name: 'Palais Garnier (Opera House) Tour',
            type: 'landmark',
            location: 'Pl. de l’Opéra, 9th Arr.',
            start_time: '14:30',
            end_time: '17:00',
            duration_minutes: 150,
            estimated_cost: 3200,
            currency: 'INR',
            description: 'Grand marble staircase, Chagall ceiling painting, and Phantom of the Opera auditorium',
            status: 'confirmed',
            status_label: 'Pass Verified',
            tags: ['Architecture', 'Opera', 'History'],
          },
          {
            id: 'act_304',
            name: 'Galeries Lafayette Rooftop & Dinner',
            type: 'dining',
            location: '40 Bd Haussmann',
            start_time: '18:00',
            end_time: '20:30',
            duration_minutes: 150,
            estimated_cost: 4600,
            currency: 'INR',
            description: 'Free open rooftop panoramic skyline sunset followed by rooftop dining',
            status: 'confirmed',
            status_label: 'Confirmed',
            tags: ['Dining', 'Rooftop', 'Sunset'],
          },
        ],
      },
      {
        day_number: 4,
        date: '2026-10-13',
        title: 'Royalty & Departure',
        theme: 'Gothic stained glass, palace archives, and return flight telemetry',
        daily_cost: 11500,
        currency: 'INR',
        walking_distance_km: 3.2,
        walking_duration_minutes: 40,
        conflicts_count: 0,
        activities: [
          {
            id: 'act_401',
            name: 'Sainte-Chapelle & Conciergerie',
            type: 'landmark',
            location: '10 Bd du Palais',
            start_time: '09:00',
            end_time: '12:00',
            duration_minutes: 180,
            estimated_cost: 2600,
            currency: 'INR',
            description: '1,113 stained glass panels dating back to the 13th century in the heart of Île de la Cité',
            status: 'confirmed',
            status_label: 'Pass Verified',
            tags: ['Gothic', 'Landmark', 'History'],
          },
          {
            id: 'act_402',
            name: 'Farewell Lunch at Le Marais',
            type: 'dining',
            location: 'Rue des Rosiers, 4th Arr.',
            start_time: '12:30',
            end_time: '14:30',
            duration_minutes: 120,
            estimated_cost: 2400,
            currency: 'INR',
            description: 'Artisan patisseries, falafel pita, and courtyard coffee in historic Marais mansion district',
            status: 'confirmed',
            status_label: 'Confirmed',
            tags: ['Food', 'Marais'],
          },
          {
            id: 'act_403_departure',
            name: 'CDG Transfer & Flight AF1825 Departure',
            type: 'flight',
            location: 'CDG Terminal 2E',
            start_time: '16:00',
            end_time: '19:30',
            duration_minutes: 210,
            estimated_cost: 1200,
            currency: 'INR',
            description: 'Fast bag drop, automated passport gates, and departure flight protocol',
            status: 'confirmed',
            status_label: 'Scheduled',
            tags: ['Flight', 'Departure'],
          },
        ],
      },
    ],
  },
};

export const MOCK_DISRUPTED_ALTERNATIVES: Alternative[] = [
  {
    id: 'alt_orsay_01',
    activity_id: 'act_002_louvre',
    name: "Musée d'Orsay",
    subtitle: 'Impressionist & 19th c. Masterpieces',
    type: 'museum',
    location: "Esplanade Valéry Giscard d'Estaing (1.2 km from Saint-Germain)",
    start_time: '10:45',
    end_time: '13:00',
    duration_minutes: 135,
    estimated_cost: 1900,
    currency: 'INR',
    description:
      'Seamless connection: 8-minute walk across Pont Royal into Tuileries lunch. Renoir, Van Gogh, Monet collections.',
    match_score: 98,
    cost_difference: -300,
    travel_time_difference: -5,
    verification_source: 'Tavily Verified Open',
    operating_hours: 'Open until 18:00 (Thursdays 21:45)',
    transit_notes: 'Direct bridge walk saves 5 mins transit overhead',
    tags: ['Art', 'French History', 'Impressionism', 'Van Gogh'],
    image_url:
      'https://images.unsplash.com/photo-1594911772125-07fc7a2d8d9f?auto=format&fit=crop&w=600&q=80',
    is_top_match: true,
  },
  {
    id: 'alt_pompidou_02',
    activity_id: 'act_002_louvre',
    name: 'Centre Pompidou & Modern Art',
    subtitle: '20th Century Masterpieces & Iconic High-Tech Architecture',
    type: 'museum',
    location: 'Place Georges-Pompidou, 4th Arr.',
    start_time: '11:00',
    end_time: '13:15',
    duration_minutes: 135,
    estimated_cost: 2100,
    currency: 'INR',
    description:
      'Modernist art collections, Kandinsky & Picasso galleries. Rooftop view over central Paris.',
    match_score: 87,
    cost_difference: -100,
    travel_time_difference: 15,
    verification_source: 'Paris Museum Services',
    operating_hours: 'Open 11:00 – 21:00',
    transit_notes: '+15 min transit delay to Tuileries lunch',
    tags: ['Modern Art', 'Architecture', 'Picasso'],
    image_url:
      'https://images.unsplash.com/photo-1549144511-f099e773c147?auto=format&fit=crop&w=600&q=80',
    is_top_match: false,
  },
  {
    id: 'alt_orangerie_03',
    activity_id: 'act_002_louvre',
    name: "Musée de l'Orangerie (Early Slot)",
    subtitle: 'Monet Water Lilies & Walter-Guillaume Collection',
    type: 'museum',
    location: 'Jardin des Tuileries (West end)',
    start_time: '10:30',
    end_time: '12:45',
    duration_minutes: 135,
    estimated_cost: 1750,
    currency: 'INR',
    description:
      'Directly adjacent to the lunch bistro inside Tuileries gardens. Eliminates external transit completely.',
    match_score: 93,
    cost_difference: -450,
    travel_time_difference: -10,
    verification_source: 'Tavily Live Feed',
    operating_hours: 'Open 09:00 – 18:00',
    transit_notes: '0 min transit to Tuileries lunch (same garden)',
    tags: ['Art', 'Monet', 'Gardens'],
    image_url:
      'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=600&q=80',
    is_top_match: false,
  },
];

export const MOCK_REPLANNED_CHANGES: ChangeSummary[] = [
  {
    type: 'activity_removed',
    event_type: 'REMOVED',
    old_activity: 'Louvre Museum Timed Entry',
    reason: 'Venue flash closure & security drill unannounced. Direct API ticket refund triggered.',
    time_range: '10:30 – 13:00',
    cost_delta: -2200,
    trigger_reason: 'Booking cancelled by venue (Site-wide labor strike notice)',
  },
  {
    type: 'activity_added',
    event_type: 'ADDED',
    new_activity: "Musée d'Orsay",
    reason: 'Instant slot match for Impressionist & 19th c. Fine Art preference. 15-min pedestrian transit window.',
    time_range: '10:45 – 13:00',
    cost_delta: 1900,
    trigger_reason: 'Matched interest (Art & History), verified open via Tavily',
  },
  {
    type: 'time_shifted',
    event_type: 'RESCHEDULED',
    old_activity: 'Tuileries Bistro Lunch',
    new_activity: 'Tuileries Bistro Lunch (13:20 – 14:35)',
    reason: 'Pushed by +5m to accommodate leisurely foot crossing via Pont Royal & Quai Voltaire.',
    time_range: '13:20 – 14:35 (was 13:15)',
    cost_delta: 0,
    time_delta_minutes: 5,
    trigger_reason: '5 min walking buffer adjustment from Orsay',
  },
];

export const MOCK_AGENT_STEPS_GENERATION: AgentStep[] = [
  { label: 'Understanding your preferences', status: 'completed', details: 'Art immersion, French cuisine, moderate pace' },
  { label: 'Finding activities', status: 'completed', details: 'Handpicked sights, cultural spots, and local bistros' },
  { label: 'Building your day-by-day itinerary', status: 'completed', details: 'Balancing museum reservations, quiet walks, dusk viewpoints' },
  { label: 'Checking schedule constraints', status: 'completed', details: 'Opening hours, transit buffers, zero conflicts verified' },
  { label: 'Calculating budget', status: 'completed', details: 'Estimated ₹45,000 against ₹50,000 ceiling (₹5,000 cushion)' },
];

export const MOCK_AGENT_STEPS_DISRUPTION: AgentStep[] = [
  { label: 'Detected affected slot', status: 'completed', details: 'Day 1, 10:30 – 13:00 (2h 30m void)' },
  { label: 'Identified downstream conflicts', status: 'completed', details: 'Tuileries walk & lunch timing buffered' },
  { label: 'Queried Tavily live data feed', status: 'completed', details: 'Open museums nearby matching Art/History preferences' },
  { label: 'Scored and ranked 3 candidates', status: 'completed', details: 'Ranked by transit overhead, rating & budget delta' },
];

export const INITIAL_CHAT_MESSAGES: AgentMessage[] = [
  {
    id: 'msg_01',
    sender: 'assistant',
    text: 'Bonjour! I am your TravelPilot Concierge. I am continuously monitoring flight telemetry, local transport, and venue schedules for your Paris trip. How can I assist you today?',
    timestamp: '10:00 AM',
  },
];
